cd ../../c3po/expt_categoryless

#FILE_NAME="./eval/model_eval_main_temp.txt"

now=$(date +'%c')
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
echo "$now" 
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 

echo "$now"
echo "BOTTLE:: POINT TRANSFORMER"
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
echo "$now" 
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#python evaluate_model.py "point_transformer" "bottle" "pre" "bottle" "shapenet" 
python evaluate_model.py "point_transformer" "bottle" "post" "table" "shapenet" 
python evaluate_model.py "point_transformer" "bottle" "post" "chair" "shapenet" 
python evaluate_model.py "point_transformer" "bottle" "post" "bottle" "shapenet" 
python evaluate_model.py "point_transformer" "bottle" "post" "laptop" "shapenet" 
python evaluate_model.py "point_transformer" "bottle" "post" "skateboard" "shapenet" 

echo "$now"
echo "CHAIR:: POINT TRANSFORMER"
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
echo "$now" 
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#python evaluate_model.py "point_transformer" "chair" "pre" "chair" "shapenet" 
python evaluate_model.py "point_transformer" "chair" "post" "table" "shapenet" 
python evaluate_model.py "point_transformer" "chair" "post" "chair" "shapenet" 
python evaluate_model.py "point_transformer" "chair" "post" "bottle" "shapenet" 
python evaluate_model.py "point_transformer" "chair" "post" "laptop" "shapenet" 
python evaluate_model.py "point_transformer" "chair" "post" "skateboard" "shapenet" 

echo "$now"
echo "LAPTOP:: POINT TRANSFORMER" 
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
echo "$now" 
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#python evaluate_model.py "point_transformer" "laptop" "pre" "laptop" "shapenet" 
python evaluate_model.py "point_transformer" "laptop" "post" "table" "shapenet" 
python evaluate_model.py "point_transformer" "laptop" "post" "chair" "shapenet" 
python evaluate_model.py "point_transformer" "laptop" "post" "bottle" "shapenet" 
python evaluate_model.py "point_transformer" "laptop" "post" "laptop" "shapenet" 
python evaluate_model.py "point_transformer" "laptop" "post" "skateboard" "shapenet" 

echo "$now"
echo "SKATEBOARD:: POINT TRANSFORMER"
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
echo "$now" 
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#python evaluate_model.py "point_transformer" "skateboard" "pre" "skateboard" "shapenet" 
python evaluate_model.py "point_transformer" "skateboard" "post" "table" "shapenet" 
python evaluate_model.py "point_transformer" "skateboard" "post" "chair" "shapenet" 
python evaluate_model.py "point_transformer" "skateboard" "post" "bottle" "shapenet" 
python evaluate_model.py "point_transformer" "skateboard" "post" "laptop" "shapenet" 
python evaluate_model.py "point_transformer" "skateboard" "post" "skateboard" "shapenet" 

echo "$now"
echo "TABLE:: POINT TRANSFORMER"
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
echo "$now" 
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#python evaluate_model.py "point_transformer" "table" "pre" "table" "shapenet" 
python evaluate_model.py "point_transformer" "table" "post" "table" "shapenet" 
python evaluate_model.py "point_transformer" "table" "post" "chair" "shapenet" 
python evaluate_model.py "point_transformer" "table" "post" "bottle" "shapenet" 
python evaluate_model.py "point_transformer" "table" "post" "laptop" "shapenet" 
python evaluate_model.py "point_transformer" "table" "post" "skateboard" "shapenet" 


# Can evaluate trained pointnet models as well.

#echo "$now"
#echo "BOTTLE:: POINTNET"
#echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#echo "$now" 
#echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#python evaluate_model.py "pointnet" "bottle" "pre" "bottle" "shapenet" 
#python evaluate_model.py "pointnet" "bottle" "post" "table" "shapenet" 
#python evaluate_model.py "pointnet" "bottle" "post" "chair" "shapenet" 
#python evaluate_model.py "pointnet" "bottle" "post" "bottle" "shapenet" 
#python evaluate_model.py "pointnet" "bottle" "post" "laptop" "shapenet" 
#python evaluate_model.py "pointnet" "bottle" "post" "skateboard" "shapenet" 
#
#echo "$now"
#echo "CHAIR:: POINTNET"
#echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#echo "$now" 
#echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#python evaluate_model.py "pointnet" "chair" "pre" "chair" "shapenet" 
#python evaluate_model.py "pointnet" "chair" "post" "table" "shapenet" 
#python evaluate_model.py "pointnet" "chair" "post" "chair" "shapenet" 
#python evaluate_model.py "pointnet" "chair" "post" "bottle" "shapenet" 
#python evaluate_model.py "pointnet" "chair" "post" "laptop" "shapenet" 
#python evaluate_model.py "pointnet" "chair" "post" "skateboard" "shapenet" 
#
#echo "$now"
#echo "LAPTOP:: POINTNET"
#echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#echo "$now" 
#echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#python evaluate_model.py "pointnet" "laptop" "pre" "laptop" "shapenet" 
#python evaluate_model.py "pointnet" "laptop" "post" "table" "shapenet" 
#python evaluate_model.py "pointnet" "laptop" "post" "chair" "shapenet" 
#python evaluate_model.py "pointnet" "laptop" "post" "bottle" "shapenet" 
#python evaluate_model.py "pointnet" "laptop" "post" "laptop" "shapenet" 
#python evaluate_model.py "pointnet" "laptop" "post" "skateboard" "shapenet" 
#
#echo "$now"
#echo "SKATEBOARD:: POINTNET"
#echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#echo "$now" 
#echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#python evaluate_model.py "pointnet" "skateboard" "pre" "skateboard" "shapenet" 
#python evaluate_model.py "pointnet" "skateboard" "post" "table" "shapenet" 
#python evaluate_model.py "pointnet" "skateboard" "post" "chair" "shapenet" 
#python evaluate_model.py "pointnet" "skateboard" "post" "bottle" "shapenet" 
#python evaluate_model.py "pointnet" "skateboard" "post" "laptop" "shapenet" 
#python evaluate_model.py "pointnet" "skateboard" "post" "skateboard" "shapenet" 
#
#echo "$now"
#echo "TABLE:: POINTNET"
#echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#echo "$now" 
#echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" 
#python evaluate_model.py "pointnet" "table" "pre" "table" "shapenet" 
#python evaluate_model.py "pointnet" "table" "post" "table" "shapenet" 
#python evaluate_model.py "pointnet" "table" "post" "chair" "shapenet" 
#python evaluate_model.py "pointnet" "table" "post" "bottle" "shapenet" 
#python evaluate_model.py "pointnet" "table" "post" "laptop" "shapenet" 
#python evaluate_model.py "pointnet" "table" "post" "skateboard" "shapenet" 

